version: "3.9"

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
